FROM python:3.10

WORKDIR /Landing

ENV DISPLAY=:0

RUN apt-get update -y

COPY env-setup.sh /Landing/env-setup.sh

RUN chmod +x /Landing/env-setup.sh
RUN ./env-setup.sh

RUN git clone https://github.com/AshGw/AES-256.git && cd AES-256

RUN pip install -r important/requirements.txt

RUN python -m containerCrypt
