FROM python:3.10

LABEL maintainer="AshGw <AshGw@user.noreply.github.com>"
LABEL version="1.0"
LABEL description="Crypt"


WORKDIR /Landing

ENV DISPLAY=:0

COPY env-setup.sh /Landing/env-setup.sh

RUN chmod +x /Landing/env-setup.sh
RUN ./env-setup.sh

RUN git clone https://github.com/AshGw/AES-256.git
RUN cd AES-256

RUN pip install -r important/requirements.txt

CMD ['python','containerCrypt.py']