FROM python:3.10

LABEL maintainer="AshGw <AshGw@user.noreply.github.com>"
LABEL version="1.0"
LABEL description="Crypt"

ENV DISPLAY=:0

WORKDIR /Landing

RUN git clone https://github.com/AshGw/AES-256.git
WORKDIR /Landing/AES-256

RUN apt-get update -y
RUN apt-get install -y git
RUN pip install --upgrade pip
RUN pip install virtualenv
RUN virtualenv vvv
RUN /bin/sh -c ". vvv/bin/activate"
RUN pip install -r important/requirements.txt

RUN chmod +x containerCrypt.py
CMD ["python", "/Landing/AES-256/containerCrypt.py"]