name : Docker hub publish
on :
  push :
    branches :
      - main
  pull_request :
    branches :
      - main
jobs :
  build_and_publish :
    runs on : ubuntu-latest
    steps :
      - name : checking out repo
        uses : actions/checkout@v2
      - name : build and tag image
        run  : docker build -t ashcrypt:latest Docker-build
      - name : login
        run : docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name : pushing to the hub
        run : docker push ashgw/ashcrypt:latest
